// import $ from 'jquery';

if (called_from != 'view_project') {
    $(window).on('load', function () {
        if (typeof window.initFlatpickr === 'function') {
            window.initFlatpickr('#project_deadline', {
                altInput: true,
                altFormat: "F j, Y",
                dateFormat: "Y-m-d",
            });
        }
    });
    $(document).ready(function () {
        $('#project_form').validate({
            ignore: [],
            rules: {
                project_name: {
                    required: true,
                    minlength: 2,
                    maxlength: 100,
                },
                status: {
                    required: true
                },
                project_deadline: {
                    required: true,
                    dateISO: true
                },
                project_desc: {
                    minlength: 10,
                    maxlength: 2000,
                }
            },
            errorPlacement: function (error, element) {
                // 1. FLATPICKR HANDLING
                if (element.attr("name") === "project_deadline" || element.hasClass("flatpickr-input")) {
                    // Find the visible input generated by Flatpickr (the one after the hidden input)
                    var visibleInput = element.nextAll('input:not([type="hidden"])').first();

                    if (visibleInput.length) {
                        error.insertAfter(visibleInput);
                    } else {
                        error.insertAfter(element);
                    }
                }
                // 2. CHOICES.JS HANDLING
                else if (element.is("select")) {
                    var choicesContainer = element.closest(".choices");
                    if (choicesContainer.length) {
                        error.insertAfter(choicesContainer);
                    } else {
                        error.insertAfter(element);
                    }
                }
                // 3. STANDARD INPUTS
                else {
                    error.insertAfter(element);
                }
            },
        })
    });
    document.querySelectorAll('select').forEach(function (selectElement) {
        selectElement.addEventListener('change', function () {
            $(this).valid(); // Clear validation error instantly upon selecting an option
        });
    });
} else {
    $(document).ready(function () {
        function updateTaskProgress() {
            let percentage = total > 0 ? Math.round((completed / total) * 100) : 0;
            $('#task-completed').text(completed);
            $('#task-total').text(total);
            $('#task-percentage').text(percentage + '%');

            $('#task-progress-bar').css('width', percentage + '%').attr('aria-valuenow', percentage);
        }

        updateTaskProgress();
    });
}
